Repository NiranjanKumar001/Profocto, pull requests merged in 2025-10, with the labels that each got.

#15 Improve global.css and preview.jsx to improve the dropdown animations
  app/globals.css
  components/preview/Preview.jsx
Labels: enhancement, Hacktoberfest2025

#20 Fix: Prevent app crash from missing NEXT_PUBLIC_CONVEX_URL
  lib/convex-client.ts
Labels: bug, good first issue, Hacktoberfest2025

#21 Fix: Multiple runtime and performance issues
  components/preview/Preview_Simple.jsx
  lib/convex-client.ts
  next.config.mjs
Labels: bug, enhancement, Hacktoberfest2025

#22 Fix: Resolve multiple code quality and runtime issues
  app/builder/[id]/page.tsx
  app/templates/page.tsx
  components/auth/AuthModal.jsx
  components/meta/Meta.js
  components/preview/Preview_Simple.jsx
  components/utility/DateRange.jsx
Labels: bug, good first issue, Hacktoberfest2025

#24 Bug-fix: Handle OAuth cancellation with toast notifications
  app/layout.tsx
  app/page.tsx
  components/auth/AuthModal.jsx
  components/hero/Hero.jsx
  package-lock.json
  package.json
Labels: enhancement, Hacktoberfest2025
